### ISSUE TITLE
Consider rewriting the tool using hugo

### ISSUE THREAD

**Issue by NathanLovato** [NathanLovato/pdf-invoices-generator#1]
Back when I wrote this invoice generator, the website generator hugo missed a few features. But now it might be a more efficient way to build a robust generator than using python:

- it's super fast
- also based on html templates
- parses csv, json and other databases
- supports partials
- now it can output the html files only, without all the taxonomy pages etc.

I've got to give this a try

**Comment by SummittDweller** [comment]
I just forked your code.  My daughter and I are avid Hugo developers so I might pick up this (closed) issue and run with it.  Thanks for sharing!

**Comment by NathanLovato** [comment]
After trying it I wouldn't recommend it. You could make it work but there'd be no benefit over using python - quite the contrary. The templating language was too limiting.
