### ISSUE TITLE
data_demo

### ISSUE THREAD

**Issue by suchaoxiao** [NathanLovato/pdf-invoices-generator#2]
could you give me input data demo formated  csv file? 
i d like to generate some picture. ths

**Comment by NathanLovato** [comment]
Hi, sorry for getting back to you so late, I think I missed your comment.

The table is like that:

date | currency | product | amount | client | country | VAT | address | payment | account
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
05/01/2019 | USD | Make your first game course | 20 | Alfred | US |   | 11 random street, Minnesota |   | paypal
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

The tool lacks a handful of features and improvements before it's ready to use by others. It also needs some docs.

**Comment by NathanLovato** [comment]
I'm closing this issue for now, I'll document the tool as part of #6
